baseurl = "https://sou553.github.io/mmd-blog/"
title = "sou553 mmd-blog"
author = "sou553"
canonifyurls = true
paginate = 3
theme = "aether"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"